project:
  type: website
  output-dir: docs
  
website:
  title: "Justin.github.io"  
  base-url: /Justin/                  # ← 프로젝트 페이지면 꼭 필요
  site-url: https://qeeeew0907.github.io/Justin/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"         # "floating"으로 하면 접히는 띄워진 사이드바
    search: true            
    contents:
      - section: "비모수"
        contents:
          - nonparamatic.Rmd

format:
  html:
    theme:
      - cosmo
      - brand  
    css: styles.css
    toc: true
    
editor: visual

