project:
  type: website
  output-dir: docs   # <- Pages에서 main / docs로 서빙

website:
  title: "Justin.github.io"
  site-url: https://justin.github.io   # 선택(권장): 정규화된 절대 URL
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: docked
    search: true
    contents:
      - section: "비모수"
        contents:
          - nonparamatic.Rmd   # 파일명/대소문자 정확히 일치해야 함

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

